#configuring port
server:
  port: 8081

# ===============================
# DB
# ===============================
spring:
  #configuring application name
  application:
    name: 'SpringArtifactClient'
  datasource:
    url: jdbc:h2:D:/Project/Java/IDEA/SpringArtifact/users;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: admin
    password: admin
    #h2:
    #console:
    #enabled: true

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql:
      true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8081/login/oauth2/code/{registrationId}
            scope:
              - openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8081/authorized
            scope:
              - api.read
              - api.create
              - api.update
              - api.delete
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000